name: Update GitHub Pages

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we get all history for rebase

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Run script to generate HTML files
        run: php script.php  # Adjust to your actual script name

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.html
          git commit -m "Daily update of generated HTML files" || exit 0
          git pull --rebase origin main  # Pull with rebase to prevent conflicts
          git push origin main
